2023-03-06 15:18:31,943 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2023-03-06 15:18:31,943 DEBUG    root            Loaded Command Group: ['gcloud', 'version']
2023-03-06 15:18:31,943 DEBUG    root            Loaded Command Group: ['gcloud', 'config']
2023-03-06 15:18:31,944 DEBUG    root            Running [gcloud.version] with arguments: [--format: "json"]
2023-03-06 15:18:31,944 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'list']
2023-03-06 15:18:31,945 DEBUG    root            Loaded Command Group: ['gcloud', 'config', 'config_helper']
2023-03-06 15:18:31,945 DEBUG    root            Running [gcloud.auth.list] with arguments: [--filter: "status=ACTIVE", --format: "value(account)", --quiet: "True", --verbosity: "warning"]
2023-03-06 15:18:31,945 DEBUG    root            Running [gcloud.config.config-helper] with arguments: [--format: "json", --quiet: "True", --verbosity: "warning"]
2023-03-06 15:18:31,947 DEBUG    root            Chosen display Format:flattened[no-pad,separator=" "] json
2023-03-06 15:18:31,947 INFO     root            Display format: "flattened[no-pad,separator=" "] json"
2023-03-06 15:18:31,946 DEBUG    root            (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "/Users/auxia/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/auxia/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/auxia/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/config/config_helper.py", line 99, in Run
    cred = store.Load(use_google_auth=True)
  File "/Users/auxia/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 565, in Load
    cred = _Load(
  File "/Users/auxia/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/core/credentials/store.py", line 733, in _Load
    raise creds_exceptions.NoActiveAccountException(
googlecloudsdk.core.credentials.exceptions.NoActiveAccountException: You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2023-03-06 15:18:31,947 INFO     ___FILE_ONLY___ {
  "Google Cloud SDK": "420.0.0",
  "bq": "2.0.86",
  "core": "2023.02.24",
  "gcloud-crc32c": "1.0.0",
  "gsutil": "5.20"
}
2023-03-06 15:18:31,947 ERROR    root            (gcloud.config.config-helper) You do not currently have an active account selected.
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
2023-03-06 15:18:31,947 INFO     ___FILE_ONLY___ 

2023-03-06 15:18:31,949 DEBUG    root            Chosen display Format:    table[title='Credentialed Accounts'](
        status.yesno(yes='*', no=''):label=ACTIVE,
        account
    ) value(account)
2023-03-06 15:18:31,950 INFO     root            Display format: "    table[title='Credentialed Accounts'](
        status.yesno(yes='*', no=''):label=ACTIVE,
        account
    ) value(account)"
2023-03-06 15:18:31,950 WARNING  root            The following filter keys were not present in any resource : status
